name: Continuous integration
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-20.04
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1
        with:
          apps: cs
      - run: "cs launch org.endpoints4s::stub-server:2.1.0 &"
      - name: Scala 2.13 tests
        run: sbt "++ 2.13 test"
      - name: Scala 3 tests
        run: |
          sbt "++ 3.3 ;coverage; test; coverageReport; coverageAggregate"
          bash <(curl -s https://codecov.io/bash)
      - name: Version Policy Check
        run: sbt versionPolicyCheck
      - name: Code formatting
        run: sbt scalafmtCheck
